apiVersion: apps/v1
kind: Deployment
metadata:
  name: hat-fe-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hat-fe-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hat-fe-svc
    spec:
      containers:
        - name: hat-fe
          image: 915947332145.dkr.ecr.ap-northeast-2.amazonaws.com/hat-fe:29
          imagePullPolicy: Always
          ports:
            - containerPort: 80
